Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "srv-web"

  # Réseau
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Dossier partagé pour le WAR
  config.vm.synced_folder "./springApp", "/vagrant/springApp"
  # Provisioning : installer Java, Maven et Tomcat
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y openjdk-8-jdk openjdk-11-jdk openjdk-17-jdk maven wget tar

    # Installer Tomcat
    cd /opt
    if [ ! -d "tomcat9" ]; then
      wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.115/bin/apache-tomcat-9.0.115.tar.gz
      tar -xvzf apache-tomcat-9.0.115.tar.gz
      mv apache-tomcat-9.0.115 tomcat9
      chmod +x tomcat9/bin/*.sh
    fi

    # Copier le WAR automatiquement si présent
    if [ -f /home/vagrant/shared/springApp-1.0.war ]; then
      cp /home/vagrant/shared/springApp-1.0.war /opt/tomcat9/webapps/
    fi
  SHELL
end