Vagrant.configure("2") do |config|
  config.vm.define "srv-web" do |srv|
    srv.vm.box = "ubuntu/focal64"
    srv.vm.hostname = "srv-web"

    srv.vm.network "private_network", ip: "192.168.56.10"
    srv.vm.network "forwarded_port", guest: 8080, host: 8080

    srv.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    srv.vm.synced_folder "./springApp", "/vagrant/springApp"

    srv.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y openjdk-8-jdk openjdk-11-jdk openjdk-17-jdk maven wget tar

      cd /opt
      if [ ! -d "tomcat9" ]; then
        wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.115/bin/apache-tomcat-9.0.115.tar.gz
        tar -xvzf apache-tomcat-9.0.115.tar.gz
        mv apache-tomcat-9.0.115 tomcat9
        chmod +x tomcat9/bin/*.sh
      fi
    SHELL
  end
end